/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/EspacioInicialColumnaInteriorAltoNS.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['el que va']}
        geometry={nodes.Columna_interna_alta_226.geometry}
        userData={{ name: 'Columna interna alta 2/2.6' }}
      />
    </group>
  )
}

useGLTF.preload('/EspacioInicialColumnaInteriorAltoNS.gltf')
