/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/trayecto/EspacioPirateriaParedInteriorAltoNI.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.pirata} geometry={nodes.Cubo33.geometry} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/trayecto/EspacioPirateriaParedInteriorAltoNI.gltf')
