/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default React.memo((props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/trayecto/EspacioPirateriaScrollTunelBajoNI.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.pirata} geometry={nodes.Cubo9.geometry} />
    </group>
  )
})

useGLTF.preload('/trayecto/EspacioPirateriaScrollTunelBajoNI.gltf')
