/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/EspacioPirateriaEscaleraExteriorNI.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['Mat.9']} position={[1, -1, -1]} geometry={nodes.Escalera.geometry} />
    </group>
  )
}

useGLTF.preload('/EspacioPirateriaEscaleraExteriorNI.gltf')
