/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { MeshStandardMaterial } from 'three';

const mat = (oldMat) => {
  const newMat = new MeshStandardMaterial({
    color: oldMat.color, 
    map: oldMat.map
})

  return newMat;
}

export default function Model(props) {
  
  const group = useRef()
  const { nodes, materials } = useGLTF('/experimento/ColumnaGiroNS.gltf')
  return (
    <group ref={group} {...props}>
      <mesh receiveShadow castShadow material={materials['Mat.2']} geometry={nodes.Columna_Ns.geometry} position={[0.655, 0, -0.655]}>
      </mesh>
    </group>
  )
}

useGLTF.preload('/experimento/ColumnaGiroNS.gltf')
