/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/experimento/Pared.gltf')
  return (
    <group ref={group} {...props}>
    <mesh castShadow receiveShadow material={materials['Mat.2']} geometry={nodes.Pared.geometry} />
      <mesh receiveShadow geometry={nodes.Pared.geometry} >
        
        <shadowMaterial color="#black" opacity={0.5} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/experimento/Pared.gltf')
