/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/experimento/ParedEsquinaNS.gltf')
  return (
    <group ref={group} {...props}>
      <mesh castShadow receiveShadow material={materials['Mat.2']} geometry={nodes.Paredesquina_Ns.geometry} />

    </group>
  )
}

useGLTF.preload('/experimento/ParedEsquinaNS.gltf')
