/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, Suspense } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { PositionalAudio } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/experimento/ParedEsquina.gltf')
  return (
    <group ref={group} {...props}>
      <mesh castShadow receiveShadow material={materials['Mat.2']} geometry={nodes.Pared_esquina.geometry} >
      </mesh>
      <Suspense fallback={null}>
        <PositionalAudio loop url="/objs-7.mp3" distance={3}/>
      </Suspense>
    </group>
  )
}

useGLTF.preload('/experimento/ParedEsquina.gltf')
