/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/experimento/prueba.gltf')
  return (
    <group castShadow receiveShadow ref={group} {...props}>
      <mesh material={materials['el que va']} geometry={nodes.Pared2.geometry} />
    </group>
  )
}

useGLTF.preload('/experimento/prueba.gltf')
