/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/experimento/SobrePuerta.gltf')
  
  return (
    <group ref={group} {...props}>
    <mesh castShadow receiveShadow material={materials['Mat.2']} geometry={nodes.Pared_puerta_Ns.geometry} position={[0.65, 0, 0]}/>

    </group>
  )
}

useGLTF.preload('/experimento/SobrePuerta.gltf')
