/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/EspacioRedSocialEsquinaCierreInteriorBajoNI.gltf')
  console.log("a")
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Mat} geometry={nodes.Cubo35.geometry} rotation={[0, 1.5 * Math.PI, 0]} />
    </group>
  )
}

useGLTF.preload('/EspacioRedSocialEsquinaCierreInteriorBajoNI.gltf')
