/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { PositionalAudio } from '@react-three/drei'
import { useAnimations } from '@react-three/drei/useAnimations'
import useLinkPosition from './useLinkPosition';
import LinkPosition from './LinkPosition';
import { LOBBY_BUBBLE } from '../../../state/bubbles/bubblesConstants'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/trayecto/LinkInicio.gltf')
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    Object.values(actions).map(x => x.play())
  }
  ,[]);


  return (
    <>
    <LinkPosition bubble={LOBBY_BUBBLE} position={props.position} globalPosition={props.globalPosition} globalRotation={props.globalRotation}/>
    <group ref={group} {...props} dispose={null}>
      <group position={[-3.2, -2.1, -12.5]}>
          <mesh name="Cubo143" material={materials['el que va']} geometry={nodes.Cubo143.geometry} >
            <Suspense fallback={null}>
              <PositionalAudio loop url="/trayecto/LinkInicial.ogg"/>
            </Suspense>
          </mesh>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/trayecto/LinkInicio.gltf')
