/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'
import { PositionalAudio } from '@react-three/drei'
import useLinkPosition from './useLinkPosition';
import LinkPosition from './LinkPosition';
import { DEEP_WEB_BUBBLE } from '../../../state/bubbles/bubblesConstants'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/trayecto/LinkDeepWeb.gltf')
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    Object.values(actions).map(x => x.play())
  }
  ,[]);

  console.log(props.position)

  return (
    <>
    <LinkPosition bubble={DEEP_WEB_BUBBLE} position={props.position} globalPosition={props.globalPosition} globalRotation={props.globalRotation}/>
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.5, 0]}>
        <mesh material={materials['Mat.4']} geometry={nodes.Deep_web1.geometry}>
          <Suspense fallback={null}>
            <PositionalAudio loop url="/trayecto/LinkDeepWeb.ogg"/>
          </Suspense>
          <mesh material={materials['Mat.4']} geometry={nodes.n2.geometry} position={[0, 0.8, 0]} />
          <mesh name="n1" material={materials['Mat.4']} geometry={nodes.n1.geometry} position={[0, 0.4, 0]} />
        </mesh>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/trayecto/LinkDeepWeb.gltf')
