/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { PositionalAudio } from '@react-three/drei'
import { useAnimations } from '@react-three/drei/useAnimations'
import useLinkPosition from './useLinkPosition';
import LinkPosition from './LinkPosition';
import { SOCIAL_NETWORK_BUBBLE } from '../../../state/bubbles/bubblesConstants'

export default React.memo((props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/trayecto/LinkRedesSociales.gltf')
  const { actions } = useAnimations(animations, group)
  
  React.useEffect(() => {
    Object.values(actions).map(x => x.play())
  }
  ,[]);

  return (
    <>
    <LinkPosition bubble={SOCIAL_NETWORK_BUBBLE} position={props.position} globalPosition={props.globalPosition} globalRotation={props.globalRotation}/>
    <group ref={group} {...props} dispose={null}>
      <mesh name="Platónico" material={materials.Mat} geometry={nodes.Platónico.geometry} rotation={[-2.79, 0, 0]} >
        <Suspense fallback={null}>
          <PositionalAudio loop url="/trayecto/LinkRedes.ogg" distance={0.3}/>
        </Suspense>
      </mesh>
    </group>
    </>
  )
})

useGLTF.preload('/trayecto/LinkRedesSociales.gltf')
