/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { PositionalAudio } from '@react-three/drei'
import { useAnimations } from '@react-three/drei/useAnimations'
import useLinkPosition from './useLinkPosition';
import LinkPosition from './LinkPosition';
import { PORN_BUBBLE } from '../../../state/bubbles/bubblesConstants'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/trayecto/LinkPorno.gltf')
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    Object.values(actions).map(x => x.play())
  }
  ,[]);

  return (
    <>
    <LinkPosition bubble={PORN_BUBBLE} position={props.position} globalPosition={props.globalPosition} globalRotation={props.globalRotation}/>
    <group ref={group} {...props} dispose={null}>
      <group position={[-3.1, -2.4, -10.5]}>
        <mesh name="Redes_sociales" material={materials.Mat} geometry={nodes.Redes_sociales.geometry}>
          <Suspense fallback={null}>
            <PositionalAudio loop url="/trayecto/LinkPorno.ogg"/>
          </Suspense>
        </mesh>
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/trayecto/LinkPorno.gltf')
