/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'
import { PositionalAudio } from '@react-three/drei'

import { useAnimations } from '@react-three/drei/useAnimations'
import useLinkPosition from './useLinkPosition';
import LinkPosition from './LinkPosition';
import { INFORMATIVE_BUBBLE } from '../../../state/bubbles/bubblesConstants'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/LinkInformacion.gltf')
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    Object.values(actions).map(x => x.play())
  }
  ,[]);

  return (
    <>
    <LinkPosition bubble={INFORMATIVE_BUBBLE} position={props.position} globalPosition={props.globalPosition} globalRotation={props.globalRotation}/>
    <group ref={group} {...props} dispose={null}>
      <mesh name="Cubo.137_1" material={materials['Mat.7']} geometry={nodes['Cubo.137_1'].geometry} >
        <Suspense fallback={null}>
          <PositionalAudio loop url="/LinkInformacion.ogg"/>
        </Suspense>
      </mesh>
    </group>
    </>
  )
}

useGLTF.preload('/LinkInformacion.gltf')
