export const LOBBY_BUBBLE = "LOBBY_BUBBLE";
export const CONTENT_BUBBLE = "CONTENT_BUBBLE";
export const PIRACY_BUBBLE = "PIRACY_BUBBLE";
export const DEEP_WEB_BUBBLE = "DEEP_WEB_BUBBLE";
export const SOCIAL_NETWORK_BUBBLE = "SOCIAL_NETWORK_BUBBLE";
export const PORN_BUBBLE = "PORN_BUBBLE";
export const INFORMATIVE_BUBBLE = "INFORMATIVE_BUBBLE";
