/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialColumnaInteriorAltoNS from './espacioInicial/EspacioInicialColumnaInteriorAltoNS';
import EspacioDeepWebColumnaInteriorBajoNS from './espacioDeepWeb/EspacioDeepWebColumnaInteriorBajoNS';
import EspacioContenidoColumnaInteriorBajoNS from './espacioContenido/EspacioContenidoColumnaInteriorBajoNS';
import EspacioInformacionColumnaInteriorAltoNS from './espacioInformacion/EspacioInformacionColumnaInteriorBajoNS';
import EspacioRedSocialColumnaInteriorAltoNS from './espacioRedSocial/EspacioRedSocialColumnaInteriorBajoNS';
import EspacioPornoColumnaInteriorBajoNS from './espacioPorno/EspacioPornoColumnaInteriorBajoNS';
import EspacioPirateriaColumnaInteriorBajoNS from './espacioPirateria/EspacioPirateriaColumnaInteriorBajoNS';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloColumnaInteriorAltoNS = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialColumnaInteriorAltoNS bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebColumnaInteriorBajoNS bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoColumnaInteriorBajoNS bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialColumnaInteriorAltoNS bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionColumnaInteriorAltoNS bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoColumnaInteriorBajoNS bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaColumnaInteriorBajoNS bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloColumnaInteriorAltoNS;
