/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialParedExteriorNS from './espacioInicial/EspacioInicialParedExteriorNS';
import EspacioDeepWebParedExteriorNS from './espacioDeepWeb/EspacioDeepWebParedExteriorNS';
import EspacioContenidoParedExteriorNS from './espacioContenido/EspacioContenidoParedExteriorNS';
import EspacioInformacionParedExteriorNS from './espacioInformacion/EspacioInformacionParedExteriorNS';
import EspacioRedSocialParedExteriorNS from './espacioRedSocial/EspacioRedSocialParedExteriorNS';
import EspacioPornoParedExteriorNS from './espacioPorno/EspacioPornoParedExteriorNS';
import EspacioPirateriaParedExteriorNS from './espacioPirateria/EspacioPirateriaParedExteriorNS';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloParedExteriorNS = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialParedExteriorNS bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebParedExteriorNS bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoParedExteriorNS bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialParedExteriorNS bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionParedExteriorNS bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoParedExteriorNS bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaParedExteriorNS bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloParedExteriorNS;
