/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialEsquinaCierreInteriorAltoNI from './espacioInicial/EspacioInicialEsquinaCierreInteriorAltoNI';
import EspacioDeepWebEsquinaCierreInteriorAltoNI from './espacioDeepWeb/EspacioDeepWebEsquinaCierreInteriorAltoNI';
import EspacioContenidoEsquinaCierreInteriorAltoNI from './espacioContenido/EspacioContenidoEsquinaCierreInteriorAltoNI';
import EspacioInformacionEsquinaCierreInteriorAltoNI from './espacioInformacion/EspacioInformacionEsquinaCierreInteriorAltoNI';
import EspacioRedSocialEsquinaCierreInteriorAltoNI from './espacioRedSocial/EspacioRedSocialEsquinaCierreInteriorAltoNI';
import EspacioPornoEsquinaCierreInteriorAltoNI from './espacioPorno/EspacioPornoEsquinaCierreInteriorAltoNI';
import EspacioPirateriaEsquinaCierreInteriorAltoNI from './espacioPirateria/EspacioPirateriaEsquinaCierreInteriorAltoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloEsquinaCierreInteriorAltoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialEsquinaCierreInteriorAltoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebEsquinaCierreInteriorAltoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoEsquinaCierreInteriorAltoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialEsquinaCierreInteriorAltoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionEsquinaCierreInteriorAltoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoEsquinaCierreInteriorAltoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaEsquinaCierreInteriorAltoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloEsquinaCierreInteriorAltoNI;
