/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialColumnaInteriorAltoNI from './espacioInicial/EspacioInicialColumnaInteriorAltoNI';
import EspacioDeepWebColumnaInteriorBajoNI from './espacioDeepWeb/EspacioDeepWebColumnaInteriorBajoNI';
import EspacioContenidoColumnaInteriorBajoNI from './espacioContenido/EspacioContenidoColumnaInteriorBajoNI';
import EspacioInformacionColumnaInteriorAltoNI from './espacioInformacion/EspacioInformacionColumnaInteriorBajoNI';
import EspacioRedSocialColumnaInteriorAltoNI from './espacioRedSocial/EspacioRedSocialColumnaInteriorBajoNI';
import EspacioPornoColumnaInteriorBajoNI from './espacioPorno/EspacioPornoColumnaInteriorBajoNI';
import EspacioPirateriaColumnaInteriorBajoNI from './espacioPirateria/EspacioPirateriaColumnaInteriorBajoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloColumnaInteriorAltoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialColumnaInteriorAltoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebColumnaInteriorBajoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoColumnaInteriorBajoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialColumnaInteriorAltoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionColumnaInteriorAltoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoColumnaInteriorBajoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaColumnaInteriorBajoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloColumnaInteriorAltoNI;
