/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialEsquinaCierreInteriorBajoNI from './espacioInicial/EspacioInicialEsquinaCierreInteriorBajoNI';
import EspacioDeepWebEsquinaCierreInteriorBajoNI from './espacioDeepWeb/EspacioDeepWebEsquinaCierreInteriorBajoNI';
import EspacioContenidoEsquinaCierreInteriorBajoNI from './espacioContenido/EspacioContenidoEsquinaCierreInteriorBajoNI';
import EspacioInformacionEsquinaCierreInteriorBajoNI from './espacioInformacion/EspacioInformacionEsquinaCierreInteriorBajoNI';
import EspacioRedSocialEsquinaCierreInteriorBajoNI from './espacioRedSocial/EspacioRedSocialEsquinaCierreInteriorBajoNI';
import EspacioPornoEsquinaCierreInteriorBajoNI from './espacioPorno/EspacioPornoEsquinaCierreInteriorBajoNI';
import EspacioPirateriaEsquinaCierreInteriorBajoNI from './espacioPirateria/EspacioPirateriaEsquinaCierreInteriorBajoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloEsquinaCierreInteriorBajoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialEsquinaCierreInteriorBajoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebEsquinaCierreInteriorBajoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoEsquinaCierreInteriorBajoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialEsquinaCierreInteriorBajoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionEsquinaCierreInteriorBajoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoEsquinaCierreInteriorBajoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaEsquinaCierreInteriorBajoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloEsquinaCierreInteriorBajoNI;
