/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialEsquinaAperturaExteriorG from './espacioInicial/EspacioInicialEsquinaAperturaExteriorG';
import EspacioDeepWebEsquinaAperturaExteriorG from './espacioDeepWeb/EspacioDeepWebEsquinaAperturaExteriorG';
import EspacioContenidoEsquinaAperturaExteriorG from './espacioContenido/EspacioContenidoEsquinaAperturaExteriorG';
import EspacioInformacionEsquinaAperturaExteriorG from './espacioInformacion/EspacioInformacionEsquinaAperturaExteriorG';
import EspacioRedSocialEsquinaAperturaExteriorG from './espacioRedSocial/EspacioRedSocialEsquinaAperturaExteriorG';
import EspacioPornoEsquinaAperturaExteriorG from './espacioPorno/EspacioPornoEsquinaAperturaExteriorG';
import EspacioPirateriaEsquinaAperturaExteriorG from './espacioPirateria/EspacioPirateriaEsquinaAperturaExteriorG';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloEsquinaAperturaExteriorG = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialEsquinaAperturaExteriorG bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebEsquinaAperturaExteriorG bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoEsquinaAperturaExteriorG bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialEsquinaAperturaExteriorG bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionEsquinaAperturaExteriorG bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoEsquinaAperturaExteriorG bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaEsquinaAperturaExteriorG bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloEsquinaAperturaExteriorG;
