/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialEscaleraExteriorNI from './espacioInicial/EspacioInicialEscaleraExteriorG';
import EspacioDeepWebEscaleraExteriorNI from './espacioDeepWeb/EspacioDeepWebEscaleraExteriorNI';
import EspacioContenidoEscaleraExteriorNI from './espacioContenido/EspacioContenidoEscaleraExteriorNI';
import EspacioInformacionEscaleraExteriorNI from './espacioInformacion/EspacioInformacionEscaleraExteriorNI';
import EspacioRedSocialEscaleraExteriorNI from './espacioRedSocial/EspacioRedSocialEscaleraExteriorNI';
import EspacioPornoEscaleraExteriorNI from './espacioPorno/EspacioPornoEscaleraExteriorNI';
import EspacioPirateriaEscaleraExteriorNI from './espacioPirateria/EspacioPirateriaEscaleraExteriorNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloEscaleraExteriorNI = (props) => {
    
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialEscaleraExteriorNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebEscaleraExteriorNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoEscaleraExteriorNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialEscaleraExteriorNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionEscaleraExteriorNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoEscaleraExteriorNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaEscaleraExteriorNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloEscaleraExteriorNI;
