/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialPuertaInteriorAltoNI from './espacioInicial/EspacioInicialPuertaInteriorAltoNI';
import EspacioDeepWebPuertaInteriorAltoNI from './espacioDeepWeb/EspacioDeepWebPuertaInteriorAltoNI';
import EspacioContenidoPuertaInteriorAltoNI from './espacioContenido/EspacioContenidoPuertaInteriorAltoNI';
import EspacioInformacionPuertaInteriorAltoNI from './espacioInformacion/EspacioInformacionPuertaInteriorAltoNI';
import EspacioRedSocialPuertaInteriorAltoNI from './espacioRedSocial/EspacioRedSocialPuertaInteriorAltoNI';
import EspacioPornoPuertaInteriorAltoNI from './espacioPorno/EspacioPornoPuertaInteriorAltoNI';
import EspacioPirateriaPuertaInteriorAltoNI from './espacioPirateria/EspacioPirateriaPuertaInteriorAltoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloPuertaInteriorAltoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialPuertaInteriorAltoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebPuertaInteriorAltoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoPuertaInteriorAltoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialPuertaInteriorAltoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionPuertaInteriorAltoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoPuertaInteriorAltoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaPuertaInteriorAltoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloPuertaInteriorAltoNI;
