/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialParedInteriorAltoNI from './espacioInicial/EspacioInicialParedInteriorAltoNI';
import EspacioDeepWebParedInteriorAltoNI from './espacioDeepWeb/EspacioDeepWebParedInteriorAltoNI';
import EspacioContenidoParedInteriorAltoNI from './espacioContenido/EspacioContenidoParedInteriorAltoNI';
import EspacioInformacionParedInteriorAltoNI from './espacioInformacion/EspacioInformacionParedInteriorAltoNI';
import EspacioRedSocialParedInteriorAltoNI from './espacioRedSocial/EspacioRedSocialParedInteriorAltoNI';
import EspacioPornoParedInteriorAltoNI from './espacioPorno/EspacioPornoParedInteriorAltoNI';
import EspacioPirateriaParedInteriorAltoNI from './espacioPirateria/EspacioPirateriaParedInteriorAltoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloParedInteriorAltoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialParedInteriorAltoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebParedInteriorAltoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoParedInteriorAltoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialParedInteriorAltoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionParedInteriorAltoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoParedInteriorAltoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaParedInteriorAltoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloParedInteriorAltoNI;
