/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialEsquinaCierreExteriorNS from './espacioInicial/EspacioInicialEsquinaCierreExteriorNS';
import EspacioDeepWebEsquinaCierreExteriorNS from './espacioDeepWeb/EspacioDeepWebEsquinaCierreExteriorNS';
import EspacioContenidoEsquinaCierreExteriorNS from './espacioContenido/EspacioContenidoEsquinaCierreExteriorNS';
import EspacioInformacionEsquinaCierreExteriorNS from './espacioInformacion/EspacioInformacionEsquinaCierreExteriorNS';
import EspacioRedSocialEsquinaCierreExteriorNS from './espacioRedSocial/EspacioRedSocialEsquinaCierreExteriorNS';
import EspacioPornoEsquinaCierreExteriorNS from './espacioPorno/EspacioPornoEsquinaCierreExteriorNS';
import EspacioPirateriaEsquinaCierreExteriorNS from './espacioPirateria/EspacioPirateriaEsquinaCierreExteriorNS';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloEsquinaCierreExteriorNS = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialEsquinaCierreExteriorNS bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebEsquinaCierreExteriorNS bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoEsquinaCierreExteriorNS bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialEsquinaCierreExteriorNS bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionEsquinaCierreExteriorNS bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoEsquinaCierreExteriorNS bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaEsquinaCierreExteriorNS bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloEsquinaCierreExteriorNS;
