/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialPuertaExteriorNS from './espacioInicial/EspacioInicialPuertaExteriorNS';
import EspacioDeepWebPuertaExteriorNS from './espacioDeepWeb/EspacioDeepWebPuertaExteriorNS';
import EspacioContenidoPuertaExteriorNS from './espacioContenido/EspacioContenidoPuertaExteriorNS';
import EspacioInformacionPuertaExteriorNS from './espacioInformacion/EspacioInformacionPuertaExteriorNS';
import EspacioRedSocialPuertaExteriorNS from './espacioRedSocial/EspacioRedSocialPuertaExteriorNS';
import EspacioPornoPuertaExteriorNS from './espacioPorno/EspacioPornoPuertaExteriorNS';
import EspacioPirateriaPuertaExteriorNS from './espacioPirateria/EspacioPirateriaPuertaExteriorNS';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloPuertaExteriorNS = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialPuertaExteriorNS bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebPuertaExteriorNS bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoPuertaExteriorNS bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialPuertaExteriorNS bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionPuertaExteriorNS bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoPuertaExteriorNS bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaPuertaExteriorNS bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloPuertaExteriorNS;
