/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialParedExteriorNI from './espacioInicial/EspacioInicialParedExteriorNI';
import EspacioDeepWebParedExteriorNI from './espacioDeepWeb/EspacioDeepWebParedExteriorNI';
import EspacioContenidoParedExteriorNI from './espacioContenido/EspacioContenidoParedExteriorNI';
import EspacioInformacionParedExteriorNI from './espacioInformacion/EspacioInformacionParedExteriorNI';
import EspacioRedSocialParedExteriorNI from './espacioRedSocial/EspacioRedSocialParedExteriorNI';
import EspacioPornoParedExteriorNI from './espacioPorno/EspacioPornoParedExteriorNI';
import EspacioPirateriaParedExteriorNI from './espacioPirateria/EspacioPirateriaParedExteriorNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloParedExteriorNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialParedExteriorNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebParedExteriorNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoParedExteriorNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialParedExteriorNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionParedExteriorNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoParedExteriorNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaParedExteriorNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloParedExteriorNI;
