/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialEsquinaAperturaInteriorAltoNI from './espacioInicial/EspacioInicialEsquinaAperturaInteriorAltoNI';
import EspacioDeepWebEsquinaAperturaInteriorAltoNI from './espacioDeepWeb/EspacioDeepWebEsquinaAperturaInteriorAltoNI';
import EspacioContenidoEsquinaAperturaInteriorAltoNI from './espacioContenido/EspacioContenidoEsquinaAperturaInteriorAltoNI';
import EspacioInformacionEsquinaAperturaInteriorAltoNI from './espacioInformacion/EspacioInformacionEsquinaAperturaInteriorAltoNI';
import EspacioRedSocialEsquinaAperturaInteriorAltoNI from './espacioRedSocial/EspacioRedSocialEsquinaAperturaInteriorAltoNI';
import EspacioPornoEsquinaAperturaInteriorAltoNI from './espacioPorno/EspacioPornoEsquinaAperturaInteriorAltoNI';
import EspacioPirateriaEsquinaAperturaInteriorAltoNI from './espacioPirateria/EspacioPirateriaEsquinaAperturaInteriorAltoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloEsquinaAperturaInteriorAltoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialEsquinaAperturaInteriorAltoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebEsquinaAperturaInteriorAltoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoEsquinaAperturaInteriorAltoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialEsquinaAperturaInteriorAltoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionEsquinaAperturaInteriorAltoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoEsquinaAperturaInteriorAltoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaEsquinaAperturaInteriorAltoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloEsquinaAperturaInteriorAltoNI;
