/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialCuboG from './espacioInicial/EspacioInicialCuboG';
import EspacioDeepWebCuboG from './espacioDeepWeb/EspacioDeepWebCuboG';
import EspacioContenidoCuboG from './espacioContenido/EspacioContenidoCuboG';
import EspacioInformacionCuboG from './espacioInformacion/EspacioInformacionCuboG';
import EspacioRedSocialCuboG from './espacioRedSocial/EspacioRedSocialCuboG';
import EspacioPornoCuboG from './espacioPorno/EspacioPornoCuboG';
import EspacioPirateriaCuboG from './espacioPirateria/EspacioPirateriaCuboG';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloCuboG = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialCuboG bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebCuboG bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoCuboG bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialCuboG bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionCuboG bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoCuboG bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaCuboG bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloCuboG;
