/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';
import {
    LOBBY_BUBBLE,
    CONTENT_BUBBLE,
    PIRACY_BUBBLE,
    DEEP_WEB_BUBBLE,
    SOCIAL_NETWORK_BUBBLE,
    PORN_BUBBLE,
    INFORMATIVE_BUBBLE
} from '../../../../state/bubbles/bubblesConstants';

import EspacioInicialPuertaInteriorBajoNI from './espacioInicial/EspacioInicialPuertaInteriorBajoNI';
import EspacioDeepWebPuertaInteriorBajoNI from './espacioDeepWeb/EspacioDeepWebPuertaInteriorBajoNI';
import EspacioContenidoPuertaInteriorBajoNI from './espacioContenido/EspacioContenidoPuertaInteriorBajoNI';
import EspacioInformacionPuertaInteriorBajoNI from './espacioInformacion/EspacioInformacionPuertaInteriorBajoNI';
import EspacioRedSocialPuertaInteriorBajoNI from './espacioRedSocial/EspacioRedSocialPuertaInteriorBajoNI';
import EspacioPornoPuertaInteriorBajoNI from './espacioPorno/EspacioPornoPuertaInteriorBajoNI';
import EspacioPirateriaPuertaInteriorBajoNI from './espacioPirateria/EspacioPirateriaPuertaInteriorBajoNI';

function SwitchComponents({ active, children }) {
    return children.filter(child => child.props.bubble === active)
}

const ModuloPuertaInteriorBajoNI = (props) => {
    return (
        <SwitchComponents active={props.currentBubble}>
            <EspacioInicialPuertaInteriorBajoNI bubble={LOBBY_BUBBLE} {...props}/>
            <EspacioDeepWebPuertaInteriorBajoNI bubble={DEEP_WEB_BUBBLE} {...props}/>
            <EspacioContenidoPuertaInteriorBajoNI bubble={CONTENT_BUBBLE} {...props}/>
            <EspacioRedSocialPuertaInteriorBajoNI bubble={SOCIAL_NETWORK_BUBBLE} {...props}/>
            <EspacioInformacionPuertaInteriorBajoNI bubble={INFORMATIVE_BUBBLE} {...props}/>
            <EspacioPornoPuertaInteriorBajoNI bubble={PORN_BUBBLE} {...props}/>
            <EspacioPirateriaPuertaInteriorBajoNI bubble={PIRACY_BUBBLE} {...props}/>
        </SwitchComponents>
    );
};

export default ModuloPuertaInteriorBajoNI;
