/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default React.memo((props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/trayecto/EspacioInicialParedInteriorAltoNS.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['el que va']}
        geometry={nodes.pared_interior_alta_n243.geometry}
        rotation={[0, 1.55, 0]}
        userData={{ name: 'pared interior alta n2.43' }}
      />
    </group>
  )
})

useGLTF.preload('/trayecto/EspacioInicialParedInteriorAltoNS.gltf')
