/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { useBox } from '@react-three/cannon'

export default React.memo((props) => {
  const group = useRef()
  
  const { nodes, materials } = useGLTF('/trayecto/EspacioInicialCuboG.gltf')
  
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['el que va']}
        geometry={nodes['Modulo_de_apollo_escalera-piso182'].geometry}
        userData={{ name: 'Modulo de apollo escalera-piso.182' }}
      />
    </group>
  )
})

useGLTF.preload('/trayecto/EspacioInicialCuboG.gltf')
