/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/trayecto/EspacioInicialPuertaInteriorAltoNI.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['el que va']}
        geometry={nodes.Puerta_alta6.geometry}
        rotation={[Math.PI, 0, Math.PI]}
        userData={{ name: 'Puerta alta.6' }}
      />
    </group>
  )
}

useGLTF.preload('/trayecto/EspacioInicialPuertaInteriorAltoNI.gltf')
