/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default React.memo((props) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/trayecto/EspacioInicialEsquinaAperturaExteriorG.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['el que va']} geometry={nodes.Plano106.geometry} userData={{ name: 'Plano.106' }} />
    </group>
  )
})

useGLTF.preload('/trayecto/EspacioInicialEsquinaAperturaExteriorG.gltf')
