/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/EspacioInicialPuertaExteriorNS.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['el que va']}
        geometry={nodes.Pared_puerta_Ns5.geometry}
        userData={{ name: 'Pared puerta Ns.5' }}
      />
    </group>
  )
}

useGLTF.preload('/EspacioInicialPuertaExteriorNS.gltf')
