// Camera

export const SET_CAMERA = "SET_CAMERA";

export const MOVE_CAMERA = "MOVE_CAMERA";

// Shapes

export const PLAY_BASIC_SHAPE = "PLAY_BASIC_SHAPE";

export const CLEAN_BASIC_SHAPE = "CLEAN_BASIC_SHAPE";

// Ambient Light

export const SET_AMBIENT_LIGHT = "SET_AMBIENT_LIGHT";

export const UPDATE_AMBIENT_LIGHT = "UPDATE_AMBIENT_LIGHT";

export const REMOVE_AMBIENT_LIGHT = "REMOVE_AMBIENT_LIGHT";

// SpotLight

export const SET_SPOT_LIGHT = "SET_SPOT_LIGHT";

export const UPDATE_SPOT_LIGHT = "UPDATE_SPOT_LIGHT";

export const REMOVE_SPOT_LIGHT = "REMOVE_SPOT_LIGHT";

// Planes

export const SET_PLANE = "SET_PLANE";

export const UPDATE_PLANE = "UPDATE_PLANE";

export const REMOVE_PLANE = "REMOVE_PLANE";


// Outline

export const ADD_OUTLINED_MESH = "ADD_OUTLINED_MESH";

export const SET_OUTLINED_MESH = "SET_OUTLINED_MESH";

// Animations

export const PLAY_RINGS_ANIMATION = "PLAY_RINGS_ANIMATION";

export const PLAY_DODECAHEDRONS_ANIMATION = "PLAY_DODECAHEDRONS_ANIMATION";

export const PLAY_TETRAHEDRONS_ANIMATION = "PLAY_TETRAHEDRONS_ANIMATION";

export const PLAY_SPHERES_ANIMATION = "PLAY_SPHERES_ANIMATION";

export const PLAY_LATHES_ANIMATION = "PLAY_LATHES_ANIMATION";

// Sound

export const PLAY_TRANSIENT_SOUND = "PLAY_TRANSIENT_SOUND";

export const PLAY_LOOP_SOUND = "PLAY_LOOP_SOUND";

export const STOP_LOOP_SOUND = "STOP_LOOP_SOUND";
